version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run build && npm run seed && npm start"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data: 